
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'KSAwss3Uplod' do
  pod 'AWSCore', :git=>'git@github.com:streamlakecloud/aws-s3-ios.git'
  pod 'AWSS3', :git=>'git@github.com:streamlakecloud/aws-s3-ios.git'
  pod 'MJExtension'
  pod 'AFNetworking'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end


